services:
  postgres:
    image: postgres:latest
    container_name: postgres.db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: projectb
    volumes:
      - pgdata:/var/lib/postgresql/data:delegated
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready"
        - "-d"
        - "db_prod"
      interval: 10s
      timeout: 15s
      retries: 3
      start_period: 10s
volumes:
  pgdata:
